spring.application.name=demo

# URL do Session Pooler (Obrigatório para sua rede IPv4/Cabo)
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres
spring.datasource.password=Pi_Unisal_2026
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate - Apenas valida o que você já criou no SQL Editor
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect