# 1. URL com a porta 6543 (Pooler)
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres

# 2. O Usuário PRECISA ter o ID do seu projeto depois do ponto
spring.datasource.username=postgres.rkockrokhjaxdxydjotc

# 3. A senha que você definiu no Supabase (sem aspas ou colchetes)
spring.datasource.password=Pi_Unisal_2026

# 4. Configurações extras para evitar erros de metadados
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true